version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - AWS_ACCOUNT_ID=950102956942
      - AWS_DEFAULT_REGION=ap-south-1
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/azentmart-instagram-agent
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com

  build:
    commands:
      - echo Build started...
      - docker build -t azentmart-instagram-agent .

  post_build:
    commands:
      - echo Tagging image...
      - docker tag azentmart-instagram-agent:latest $REPOSITORY_URI:latest
      - echo Pushing image...
      - docker push $REPOSITORY_URI:latest

artifacts:
  files:
    - '**/*'
