import { Injectable } from '@nestjs/common';
import { ToolDefinition } from '../tools/tools.types.js';

@Injectable()
export class ToolRegistryService {
  private readonly tools: ToolDefinition[] = [
    
    {
      name: 'get_transactions',
      description: 'Get customer transaction history',
      riskLevel: 'LOW',
      requiresAuthentication: true,
      requiresMFA: false,
      requiresApproval: false,
    },
    {
      name: 'get_transaction',
      description: 'Get details of a specific transaction',
      riskLevel: 'LOW',
      requiresAuthentication: true,
      requiresMFA: false,
      requiresApproval: false,
    },
    {
      name: 'validate_transfer',
      description: 'Validate a fund transfer',
      riskLevel: 'MEDIUM',
      requiresAuthentication: true,
      requiresMFA: false,
      requiresApproval: false,
    },
    {
  name: 'prepare_transfer',
  description: 'Prepare a money transfer and return confirmation details',
  riskLevel: 'HIGH',
  requiresAuthentication: true,
  requiresMFA: true,
  requiresApproval: true,
},
    {
      name: 'confirm_transfer',
      description: 'Confirm a fund transfer',
      riskLevel: 'HIGH',
      requiresAuthentication: true,
      requiresMFA: true,
      requiresApproval: true,
    },
    {
      name: 'execute_transfer',
      description: 'Execute a fund transfer',
      riskLevel: 'HIGH',
      requiresAuthentication: true,
      requiresMFA: true,
      requiresApproval: true,
    },
    {
      name: 'generate_otp',
      description: 'Generate an MFA OTP',
      riskLevel: 'MEDIUM',
      requiresAuthentication: true,
      requiresMFA: false,
      requiresApproval: false,
    },
    {
      name: 'verify_mfa',
      description: 'Verify customer MFA',
      riskLevel: 'HIGH',
      requiresAuthentication: true,
      requiresMFA: true,
      requiresApproval: false,
    },
    {
  name: 'get_beneficiary',
  description: 'Find a beneficiary by customer ID and name',
  riskLevel: 'LOW',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
  name: 'get_beneficiaries',
  description: 'Get all beneficiaries for a customer',
  riskLevel: 'LOW',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},

{
  name: 'confirm_beneficiary',
  description: 'Confirm the provided beneficiary details before adding the beneficiary',
  riskLevel: 'HIGH',
  requiresAuthentication: true,
  requiresMFA: true,
  requiresApproval: true,
},
{
  name: 'get_balance',
  description: 'Get the available balance of a customer account',
  riskLevel: 'LOW',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
  name: 'assess_risk',
  description: 'Assess the risk of a money transfer',
  riskLevel: 'MEDIUM',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
  name: 'evaluate_policy',
  description: 'Evaluate security policy for a transfer',
  riskLevel: 'MEDIUM',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
  name: 'get_loans',
  description: 'Get customer loan details',
  riskLevel: 'LOW',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
name: 'create_loan',
description:'Create a new loan for the authenticated customer after explicit confirmation.',
  riskLevel: 'HIGH',
    requiresMFA: false,
  requiresAuthentication: true,
  requiresApproval: true,
},
{
  name: 'get_loan_balance',
  description: 'Get outstanding balance for a specific loan',
  riskLevel: 'LOW',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
  name: 'get_loan_schedule',
  description: 'Get repayment schedule for a specific loan',
  riskLevel: 'LOW',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
  name: 'make_loan_payment',
  description: 'Make a payment toward a specific loan',
  riskLevel: 'HIGH',
  requiresAuthentication: true,
  requiresMFA: true,
  requiresApproval: true,
},
{
  name: 'confirm_loan_payment',
  description: 'Confirm and execute a pending loan payment',
  riskLevel: 'HIGH',
  requiresAuthentication: true,
  requiresMFA: true,
  requiresApproval: true,
},
{
  name: 'generate_statement',
  description: 'Generate a bank statement for a customer account',
  riskLevel: 'LOW',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},

{
  name: 'get_statement',
  description: 'Retrieve a previously generated bank statement',
  riskLevel: 'LOW',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
  name: 'validate_beneficiary',
  description: 'Validate beneficiary bank account details before adding a new beneficiary',
  riskLevel: 'MEDIUM',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
  name: 'email_statement',
  description: 'Email a bank statement to the customer',
  riskLevel: 'MEDIUM',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
  name: 'get_transaction_status',
  description: 'Get the current status and details of a bank transaction',
  riskLevel: 'LOW',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
  name: 'assess_fraud',
  description: 'Assess a transaction for fraud risk',
  riskLevel: 'HIGH',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
  name: 'create_fraud_review',
  description: 'Send a high-risk transaction for human fraud review',
  riskLevel: 'HIGH',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
  name: 'get_pending_fraud_reviews',
  description: 'Get transactions waiting for human fraud review',
  riskLevel: 'MEDIUM',
  requiresAuthentication: true,
  requiresMFA: false,
  requiresApproval: false,
},
{
  name: 'approve_fraud_review',
  description: 'Approve a transaction after human fraud review',
  riskLevel: 'HIGH',
  requiresAuthentication: true,
  requiresMFA: true,
  requiresApproval: true,
},
  ];

  getAllTools(): ToolDefinition[] {
    return this.tools;
  }

  getTool(name: string): ToolDefinition | undefined {
    return this.tools.find(tool => tool.name === name);
  }
}